export {
  LIVE_LEGACY_CONNECTORS_ENABLED,
  type ReadOnlyLegacyConnector,
} from "./read-only.js";
export type { ReadOnlyAzureDevOpsConnector } from "./azure-devops/index.js";
export {
  LegacySqlConfigurationError,
  LegacySqlConnector,
  LegacySqlConnectorError,
  LegacySqlReadGuardError,
  LegacySqlRowLimitError,
  LegacySqlTableNotAllowedError,
  LegacyRelationshipSampleLimitError,
  LegacyRelatedVstsLimitError,
  LegacySharepointIdError,
  LegacyUserRequestFilterError,
  LegacyUserRequestRowLimitError,
  LEGACY_RELATIONSHIP_SAMPLE_LIMIT,
  LEGACY_USER_REQUEST_DETAIL_LIMIT,
  LEGACY_USER_REQUEST_TABLE,
  LEGACY_VSTS_TABLE,
  MAX_LEGACY_MATRIX_ROWS,
  MAX_LEGACY_USER_REQUEST_ROWS,
  MAX_RELATED_VSTS_ITEMS,
  MssqlLegacySqlDriver,
  assertLegacySqlReadOnlyQuery,
  analyzeLegacyApprovalLifecycleRows,
  analyzeLegacyUserRequestVstsRows,
  buildLegacyApprovalPresencePatternQuery,
  buildLegacyApprovalContinuationSummaryQuery,
  buildLegacyApprovalStatusDistributionQuery,
  buildLegacyCrossSourceDateOrderingQuery,
  buildLegacyDatePatternQuery,
  buildLegacyDateOrderingQuery,
  buildLegacyDateTimeSemanticsQuery,
  buildLegacyMultipleVstsSummaryQuery,
  buildLegacyMultipleVstsTypeStateQuery,
  buildLegacyOpenCaseCorrelationQuery,
  buildLegacyOpenCaseApprovalCorrelationQuery,
  buildLegacyOpenCaseStatusCorrelationQuery,
  buildLegacyStatusMismatchPatternQuery,
  buildLegacyStatusMismatchSummaryQuery,
  buildLegacyVstsDuplicateSummaryQuery,
  buildLegacyVstsStatusDistributionQuery,
  buildLegacyUserRequestDetailQuery,
  buildLegacyUserRequestListQuery,
  buildRelatedVstsItemsQuery,
  buildLegacyUserRequestRelationshipSampleQuery,
  buildLegacyUserRequestVstsColumnsQuery,
  buildLegacyUserRequestVstsIndexesQuery,
  buildLegacyVstsRelationshipSampleQuery,
  buildLegacyProductManagementMatrixQuery,
  enforceLegacyMatrixRowLimit,
  enforceLegacyRelationshipSampleLimit,
  enforceLegacySharepointId,
  enforceLegacyUserRequestRowLimit,
  enforceRelatedVstsLimit,
  getLegacyProductManagementMatrixTable,
  matrixSources,
  legacyUserRequestFilterKeys,
  normalizeLegacyUserRequestFilters,
  normalizeLegacyWorkId,
  classifySemanticEvidence,
  readLegacySqlConfig,
  type LegacyProductManagementMatrixRow,
  type LegacyRelatedVstsItemRow,
  type LegacyRelatedVstsRows,
  type LegacyUserRequestRow,
  type LegacyUserRequestDetailRow,
  type LegacyUserRequestFilterKey,
  type LegacyRelationshipClassification,
  type LegacyRelationshipSampleRow,
  type LegacyRelationshipSummary,
  type LegacySchemaColumn,
  type LegacyUniqueIndexColumn,
  type ApprovalPresencePattern,
  type LegacyApprovalLifecycleSummary,
  type LegacyLifecycleSharePointObservation,
  type LegacyLifecycleVstsObservation,
  type SemanticClassification,
  type SemanticFinding,
  type SemanticValueCount,
  type LegacySqlConfig,
  type LegacySqlDriver,
  type LegacySqlEnvironment,
  type LegacySqlParameter,
  type LegacySqlParameterValue,
  type LegacySqlPool,
  type LegacySqlQuery,
  type LegacySqlRequest,
  type MatrixSource,
  type ReadOnlyLegacySqlConnector,
} from "./legacy-sql/index.js";
export type { ReadOnlySharePointConnector } from "./sharepoint/index.js";
