export {
  LIVE_LEGACY_CONNECTORS_ENABLED,
  type ReadOnlyLegacyConnector,
} from "./read-only.js";
export type { ReadOnlyAzureDevOpsConnector } from "./azure-devops/index.js";
export {
  LegacySqlConfigurationError,
  LegacySqlConnector,
  LegacySqlConnectorError,
  LegacySqlReadGuardError,
  LegacySqlRowLimitError,
  LegacySqlTableNotAllowedError,
  LegacyRelationshipSampleLimitError,
  LegacyUserRequestRowLimitError,
  LEGACY_RELATIONSHIP_SAMPLE_LIMIT,
  LEGACY_USER_REQUEST_TABLE,
  LEGACY_VSTS_TABLE,
  MAX_LEGACY_MATRIX_ROWS,
  MAX_LEGACY_USER_REQUEST_ROWS,
  MssqlLegacySqlDriver,
  assertLegacySqlReadOnlyQuery,
  analyzeLegacyUserRequestVstsRows,
  buildLegacyUserRequestListQuery,
  buildLegacyUserRequestRelationshipSampleQuery,
  buildLegacyUserRequestVstsColumnsQuery,
  buildLegacyUserRequestVstsIndexesQuery,
  buildLegacyVstsRelationshipSampleQuery,
  buildLegacyProductManagementMatrixQuery,
  enforceLegacyMatrixRowLimit,
  enforceLegacyRelationshipSampleLimit,
  enforceLegacyUserRequestRowLimit,
  getLegacyProductManagementMatrixTable,
  matrixSources,
  normalizeLegacyWorkId,
  readLegacySqlConfig,
  type LegacyProductManagementMatrixRow,
  type LegacyUserRequestRow,
  type LegacyRelationshipClassification,
  type LegacyRelationshipSampleRow,
  type LegacyRelationshipSummary,
  type LegacySchemaColumn,
  type LegacyUniqueIndexColumn,
  type LegacySqlConfig,
  type LegacySqlDriver,
  type LegacySqlEnvironment,
  type LegacySqlParameter,
  type LegacySqlParameterValue,
  type LegacySqlPool,
  type LegacySqlQuery,
  type LegacySqlRequest,
  type MatrixSource,
  type ReadOnlyLegacySqlConnector,
} from "./legacy-sql/index.js";
export type { ReadOnlySharePointConnector } from "./sharepoint/index.js";
