import type { ProductManagementFormDefinition } from "@access-portal/contracts";
import { useEffect, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { PageHeader } from "../components/PageHeader.js";
import { StatusBadge } from "../components/StatusBadge.js";
import type { ProductManagementApiClient } from "../requests/productManagementApi.js";

const countries = ["Thailand", "Vietnam"] as const;
const topics = ["New Product", "Product Change"] as const;
export function NewProductManagementRequestPage({ api }: { readonly api: Pick<ProductManagementApiClient, "form" | "submit"> }) {
  const navigate = useNavigate(); const [country, setCountry] = useState(""); const [topic, setTopic] = useState(""); const [form, setForm] = useState<ProductManagementFormDefinition | null>(null); const [fields, setFields] = useState<Record<string, string>>({}); const [state, setState] = useState<"ready" | "loading" | "saving" | "error">("ready"); const ready = Boolean(country && topic);
  useEffect(() => { if (!ready) { setForm(null); return; } let active = true; setState("loading"); api.form(country, topic).then((value) => { if (active) { setForm(value); setFields({}); setState("ready"); } }).catch(() => { if (active) setState("error"); }); return () => { active = false; }; }, [api, country, topic, ready]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form || form.fields.some((field) => field.required && !fields[field.key]?.trim())) return; setState("saving"); try { await api.submit({ country, topic, fields, idempotencyKey: crypto.randomUUID() }); navigate("/requests"); } catch { setState("error"); } };
  return <div className="page"><PageHeader eyebrow="Product Management" title="New Request" description="MVP form only. Submission is a mock API contract and does not call USR_PowerApp or an existing workflow." actions={<StatusBadge tone="info">No production write</StatusBadge>} />
    <form className="panel request-form" onSubmit={(event) => void submit(event)}><div className="panel-heading"><div><p className="panel-kicker">Step 1</p><h2>Request context</h2></div><StatusBadge tone="neutral">System fixed</StatusBadge></div><div className="request-form__grid"><label className="field"><span>System</span><input value="Product Management" readOnly /></label><label className="field"><span>Country</span><select value={country} onChange={(event) => setCountry(event.target.value)}><option value="">Select country</option>{countries.map((value) => <option key={value}>{value}</option>)}</select></label><label className="field"><span>Topic</span><select value={topic} onChange={(event) => setTopic(event.target.value)}><option value="">Select topic</option>{topics.map((value) => <option key={value}>{value}</option>)}</select></label></div>
      {form ? <><div className="panel-heading request-form__step"><div><p className="panel-kicker">Step 2</p><h2>{country} · {topic}</h2></div></div><div className="request-form__grid">{form.fields.map((field) => <label key={field.key} className="field request-form__reason"><span>{field.label}{field.required ? " *" : ""}</span>{field.type === "textarea" ? <textarea required={field.required} value={fields[field.key] ?? ""} onChange={(event) => setFields({ ...fields, [field.key]: event.target.value })} /> : field.type === "select" ? <select required={field.required} value={fields[field.key] ?? ""} onChange={(event) => setFields({ ...fields, [field.key]: event.target.value })}><option value="">Select</option>{field.options?.map((option) => <option key={option}>{option}</option>)}</select> : <input required={field.required} value={fields[field.key] ?? ""} onChange={(event) => setFields({ ...fields, [field.key]: event.target.value })} />}</label>)}</div><button className="button button--primary" disabled={state === "saving"} type="submit">{state === "saving" ? "Submitting…" : "Submit mock request"}</button></> : null}{state === "error" ? <p role="alert" className="request-form__message">The mock Product Management API is unavailable. No request was sent.</p> : null}</form>
  </div>;
}
